### PR TITLE
Added long description for package

### PR DESCRIPTION
**Pull request by kamikaz1k**
Refs TNG-000

### CODE REVIEW

**Review by amcintosh — APPROVED** [review]

**Comment by kamikaz1k** [comment]
@drone115b do I need to do a version bump before merging?

**Comment by ajsridha** [comment]
Good job!

**Comment by AntonNguyen** [comment]
@kamikaz1k No reason why you can't bump the version in `setup.cfg` and `setup.py` in this PR. 👍

**Comment by drone115b** [comment]
@kamikaz1k Yes, thanks, I'm fine with doing a version bump.  I'll be doing another release soon (<2 days) so either way I'll take care of it.

**Comment by drone115b** [comment]
@kamikaz1k (FWIW, There's a "make bump" for incrementing the release version.)

**Comment by drone115b** [comment]
@kamikaz1k  I have a PR in which I will want to release as 1.11.6.    I'm merging your changes here in and I've taken care of version bump.

**Pull request merged**
